### ISSUE TITLE
Banzai is strangely opaque on GitHub search 

### ISSUE THREAD

**Issue by 10Dev** [banzaicloud/pipeline#1053]
I am in the early stage of constructing a comprehensive list of resources for machine learning types of workloads on Kubernetes.

https://github.com/CognonicLabs/awesome-AI-kubernetes

In the process of doing this I perform regular searches on GitHub using simple terms like "kubeflow" or "pachyderm" etc which produce expected results

When searching "banzai" or "banzai cloud" or "banzaicloud" I get surprisingly few results.

Perhaps the keywords in your project descriptions are just off some mark a little bit or Topic Listings or something I'm not aware of is affecting things, but I can't imagine that any team on GitHub would be happy about a strangely small footprint.

Also, I'd welcome any improvements in my description or categorization of your various projects

**Comment by matyix** [comment]
Those "keywords" you have actually mentioned are unique words, whereas `banzai` or `cloud` is used  elsewhere as well. If. you search for `banzaicloud` it's actually OK. At the end this is a GitHub search indexing `issue` and there is not much we can do about.

**Comment by 10Dev** [comment]
This search:

https://github.com/search?q=banzaicloud

has 3 results

You have more than that just within your own org.

Just trying to be helpful, but if you are happy with that, then just ignore my input which of course you just did :)

**Comment by matyix** [comment]
I have not ignored it, I did answer and have actually tested it - a `pachyderm` search shows up exactly 6 repositories from their repository, whereas they have more (12 public) repositories. Do the same for `kubeflow` and you will see the result (10 results for 22 repositories).
