### ISSUE TITLE
Add values parameter to Ingress and Monitoring Posthooks, to enable fine tuning helm charts

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/pipeline#1316]
For example in case of Alibaba the chart values should be set to use at least 20GI size as a Persistent Volume

**Comment by sagikazarmark** [comment]
Posthooks will be superseded by features and we don't intend to support arbitrary chart values for the simple reason that they aren't necessarily helm chart installations. These issues will have to be solved individually.
