### ISSUE TITLE
Deleting cluster fails if it was still being created

### ISSUE THREAD

**Issue by orymate** [banzaicloud/pipeline#1323]
**Describe the bug**
If I create a cluster, but delete it before it becomes ready, the transitions into ERROR: "There's no secret with this ID" status.

**Steps to reproduce the issue:**

* create cluster
* delete cluster immediately

**Expected behavior**
Either
* http400 for the deletion if cluster is in creating state, or
* cancel the creation somehow

Also
* store the used secret id initially (when the db record is created)

**Comment by akijakya** [comment]
The issue has been resolved in #3587 by returning 409 Conflict error if deletion is called upon a cluster in CREATING status, however, it can be overwritten by force deleting it (adding the -f flag in banzai CLI or uncheck the graceful delete option on the GUI).
