### ISSUE TITLE
Delete more than one deployment

### ISSUE THREAD

**Issue by colin014** [banzaicloud/pipeline#1338]
We need an API endpoint which can handle more than one deployment delete by release names.
The url should be something like this:
`{{url}}/api/v1/orgs/:orgId/clusters/:clusterId/deployments/:deploymentName1,:deploymentName2`

**Comment by sagikazarmark** [comment]
For now, the UI will send separate requests for deleting deployments. Error reporting and parallelization of seems to be an unnecessary hassle on the backend side.
