### ISSUE TITLE
Use common retry/backoff implementation

### ISSUE THREAD

**Issue by orymate** [banzaicloud/pipeline#1351]
There are at least three implementations of retry (with optional backoff) logic in our code. Use a common one, either own implementation or from a library.

> BUT: I would rather say, that we should probably use some sort of backoff library: https://medium.com/@lestrrat/yak-shaving-with-backoff-libraries-in-go-80240f0aa30c Ultimately this code go into a pkg/backoff package itself, but there are already great implementations for that.

From #1344 comments

**Comment by sagikazarmark** [comment]
Looks like this has been resolved.
