### ISSUE TITLE
Synchronize Github organizations

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pipeline#1375]
Add new Github organizations

**Comment by orymate** [comment]
how does this relate to #1324?

**Comment by sagikazarmark** [comment]
When a user gets added to a new organization, currently it's not being propagated to Pipeline automatically (just like in case of any services that rely on github organization list). We need an API endpoint for synchronizing Github organizations and as per some discussions this will be an add-only operation, we don't remove users from organizations (for now).
