### ISSUE TITLE
Private OAuth & Cloud VPC support

### ISSUE THREAD

**Issue by stevenpeh** [banzaicloud/pipeline#1476]
Hi, reading through the docs, it seems Pipeline only supports Github OAuth and the cloud demos seems to provision Public IPs.

We are looking at multi-cloud control planes and pipeline seems like a good tool to evaluate.

However, as a highly regulated organization, we really can't have external OAuth providers like github and also creating public internet facing endpoints (even though we can firewall it).  We'd like to use our own internal OAuth and also have the pipeline control plane installed in our own private VPCs in our cloud account and use it to provision/manage GKE and EKS.

Is this in the roadmap for pipeline?

**Comment by matyix** [comment]
Hi @stevenpeh 

Yes, the control plane can be hosted anywhere - as it requires K8s only. We have automated installations for several providers (including Google and AWS as per your selected cloud).

For other OAuth providers - yes, there is work ongoing to integrate with [dex](https://github.com/dexidp/dex) but we might switch to another OIDC alternative. Regardless, yes it's in the very near roadmap to have alternative options besides GitHub.

If you are interested to discuss it further and get a private control plane installation drop me a mail at janos@banzaiclod.com

**Comment by bonifaido** [comment]
The OIDC part has been merged to master.
