### ISSUE TITLE
GitHub repository check

### ISSUE THREAD

**Issue by colin014** [banzaicloud/pipeline#1482]
Need a new API endpoint which can verify that the user has already such a repository.

Endpoint should be something like this: 
`GET /api/v1/github/repository/:repoName`

**Comment by sagikazarmark** [comment]
If it is just verification, it should be `HEAD`. Also, is this limited to the user's own repositories? Or do we need to check organization repositories?

Since it's a ui related call, could this go under the dashboard endpoint?

**Comment by sagikazarmark** [comment]
Spotguides are discontinued.
