### ISSUE TITLE
Create monitored cluster with name containing `_` fails

### ISSUE THREAD

**Issue by orymate** [banzaicloud/pipeline#1547]
**Describe the bug**
Creation of a cluster with monitoring enabled and its name containing `_` fails 

**Steps to reproduce the issue:**
* Create cluster with monitoring enabled and a cluster name containing an underscore (possible at least with AKS).
* Will get ERROR state with monitoring:
```status":"ERROR","statusMessage":"install pipeline-cluster-monitor failed: Error deploying chart: rpc error: code = Unknown desc = release monitor failed: Ingress.extensions \"monitor-grafana\" is invalid: spec.rules[0].host: Invalid value: \"orymatejzs_z.orymate.XXX": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","name":"orymatejzs_z",```

**Expected behavior**
success. we should map cluster names (clusters) somehow to unique dns compliant names

**Comment by sagikazarmark** [comment]
Monitoring has been rewritten as integrated service.
