### ISSUE TITLE
Support adding labels to node pools

### ISSUE THREAD

**Issue by stoader** [banzaicloud/pipeline#1579]
Pipeline already automatically applies labels to nodes of a node pool during cluster creation such as:

- **nodepool.banzaicloud.io/name** -> `<name of the nodepool>`
- **node.banzaicloud.io/ondemand** -> `<true for ondemand nodes, false for preemptive nodes>` (used by our custom scheduler for ondemand/spot instance percentage deployments)

Pipeline API needs to support adding any custom labels to node pools in order to leverage the various node instance metadata provided by Cloud Info. The Pipeline will pull instance types, price info, regions etc from Cloud Info and set these as node labels. This way these instance metadata become available inside the K8s cluster (and be used by e.g. advanced scheduling scenarios).

The payload for specifying labels for node pools:
```
"nodePools": {
        ...
        "<name>": {
            ...
            "labels": {
                "label1": "value1",
                "label2", "value2"
            }
            ...
        },
```

Users should be able to specify node label during cluster creation/update they want to place on the nodes of a nodepool. These will be added to nodes in addition to what comes from Cloud Info.

If the user specifies the same label name as what Pipeline uses than the user’s settings will override the Pipeline provided value.

**Comment by sagikazarmark** [comment]
> If the user specifies the same label name as what Pipeline uses than the user’s settings will override the Pipeline provided value.

Is this a good idea? Do we rely on those labels? If yes, we shouldn't allow the user to do that, should we?

**Comment by waynz0r** [comment]
+1 for not a good idea to allow users to overwrite Pipeline labels

**Comment by stoader** [comment]
Agree that Pipeline provided labels should not be overridable as Pipeline relies on those.

**Comment by smartyjohn** [comment]
There does need to be some distinction between node pools, e.g. pipeline/system and worker node pools in particular. That is, labels added to nodes may only apply to one, some, or all node pools.  I believe it would be sufficient if each node pool's labels were managed separately.
