### ISSUE TITLE
Check the proper way of setting a column's SQL type to TEXT

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pipeline#1600]
Currently in the repository we use `sql:"type:text;"` struct tags to indicate TEXT type in the schema, but as @orymate spotted there is no reference to this in the GORM documentation.

- [x] Check that `sql:"type:text;"` is still valid (and not deprecated) and check if there is a best practice to use `gorm:"type:text;"` instead.
- [ ] Use `gorm:` everywhere to prevent confusion.

**Comment by stoader** [comment]
https://github.com/jinzhu/gorm/issues/744

Apparently there is no reference to `sql` struct tag in the documentation however we can find out how the `sql` tags is being used from the source code: https://github.com/jinzhu/gorm/blob/master/model_struct.go#L627

**Comment by sagikazarmark** [comment]
Looks like there is no better option than what we are doing today.
