### ISSUE TITLE
Validate configuration on start

### ISSUE THREAD

**Issue by tothandras** [banzaicloud/pipeline#1627]
**Is your feature request related to a problem? Please describe.**

Pipeline can be started with bad configuration. It will only fail once those certain values are used (eg. on an API request).

**Describe the solution you'd like to see**

Validate the configuration on start.

**Additional context**

https://blog.acolyer.org/2016/11/29/early-detection-of-configuration-errors-to-reduce-failure-damage/

**Comment by sagikazarmark** [comment]
Done as part of the config refactor.
