### ISSUE TITLE
Casbin support for multi-tenancy?

### ISSUE THREAD

**Issue by judahb** [banzaicloud/pipeline#1629]
**Is your feature request related to a problem? Please describe.**
Looking to support multi-tenant design

**Describe the solution you'd like to see**
Looking for Casbin support of RBAC with domains/tenants

**Describe alternatives you've considered**
considering Casbin is implemented the approach above should be least friction to implement

**Comment by sagikazarmark** [comment]
@judahb we decided to remove casbin (at least for now) as the costs outweighed the benefits. See #1758 and #1764 for details.
