### ISSUE TITLE
ScrapeSharedSpotguides logic is flawed

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/pipeline#1644]
**Describe the bug**
Shared spotguides are synced from https://github.com/spotguides repository. This organization has to exist in the database up-front to support the current implementation:

```go
func NewSpotguideManager(db *gorm.DB, pipelineVersionString string, githubToken string, sharedLibraryGitHubOrganization string) *SpotguideManager {
	sharedLibraryOrganization, err := auth.GetOrganizationByName(sharedLibraryGitHubOrganization)
	if err != nil {
		log.Errorf("shared spotguide organization (%s) is not found", sharedLibraryGitHubOrganization)
	}
```

When a user does a clean installation of pipeline, and would like to use spotguides and is not part of the aforementioned organization, won't be able to use our spotguides.

**Steps to reproduce the issue:**
Start pipeline on your machine, and login with a GitHub user who is not part of the organization.

**Expected behavior**
Everybody should be able to use the shared spotguides.

**Comment by sagikazarmark** [comment]
It might make sense not to insert the organization into the database in the first place and just use configuration to determine the spotguide organization.
