### ISSUE TITLE
Define getClusterDetails() (ACK) method at one place

### ISSUE THREAD

**Issue by Laci21** [banzaicloud/pipeline#1715]
**Is your feature request related to a problem? Please describe.**
The `getClusterDetails()` method is implemented in two different packages with very similar functionality:
- https://github.com/banzaicloud/pipeline/blob/master/pkg/cluster/acsk/action/action_utils.go#L255
- https://github.com/banzaicloud/pipeline/blob/master/cluster/acsk.go#L422

**Describe the solution you'd like to see**
There should be only one implementation which is called uniformly everywhere from the codebase. It is not clear which to keep though, need to investigate.

**Comment by sagikazarmark** [comment]
My guess is it's duplicated because the original method was unexported.

**Comment by sagikazarmark** [comment]
ACSK needs a complete rewrite
