### ISSUE TITLE
Cadence auth support

### ISSUE THREAD

**Issue by kozmagabor** [banzaicloud/pipeline#1780]
**Is your feature request related to a problem? Please describe.**
We should communicate over a secure and authenticated channel between pipeline and temporal.

**Comment by sagikazarmark** [comment]
https://github.com/square/ghostunnel

**Comment by mfateev** [comment]
Cadence team targets the release of TLS support by the end of August. 

https://github.com/uber/cadence/issues/2018

**Comment by sagikazarmark** [comment]
That's good to know, thanks!

**Comment by sagikazarmark** [comment]
TLS support in Temporal:

https://github.com/temporalio/temporal/issues/304

**Comment by sagikazarmark** [comment]
Cadence will not receive an auth layer. It will be available in Temporal.
