### ISSUE TITLE
Cannot activate repo in CI/CD

### ISSUE THREAD

**Issue by petivagyok16** [banzaicloud/pipeline#1812]
**Describe the bug**
I was unable to activate any of my repos in CI/CD
Request preview:
`Request URL: https://local.dev.banzaicloud.com/api/build/api/repos/petivagyok16/spark-pdi-example`
`400 Bad Request [failed to create Pipeline token on API]`

**Expected behavior**
Be able to activate repo, or give me back a meaningful error message.

**Additional context**
This is a not properly handled error, so we don't know any details about the error, so we show only an `Error` message for the user.
```
Request Method: POST
Status Code: 500 Internal Server Error
400 Bad Request [failed to create Pipeline token on API]
```

**Comment by bonifaido** [comment]
Fixed in CI/CD.
