### ISSUE TITLE
Change login redirect logic

### ISSUE THREAD

**Issue by colin014** [banzaicloud/pipeline#1905]
**Describe the solution you'd like to see**
Currently if the user is a brand new user we navigate to the signup form else we navigate to dashboard. 
Change this behaviour to:
- [ ] If the user is a brand new user and there’s no DEX connectors navigate to `{{url}}/authentication`. I think this url should came from config 
- [ ] Make configurable we need to redirect to signup form or not
- [ ] If the user hasn’t a valid cookie/token and there’s at least one connector for DEX navigate to DEX login flow

**Comment by sagikazarmark** [comment]
Closing as we chose a different path for installing Pipeline.
