### ISSUE TITLE
GitHub OAuth app settings

### ISSUE THREAD

**Issue by colin014** [banzaicloud/pipeline#1906]
**Describe the solution you'd like to see**
Set GitHub OAuth app in runtime.

We need a new API endpoint to set GitHub OAuth app, two field is required:
- clientID
- secretID

The new endpoint should be look like something like this: `POST /auth/:type` (in this case `type` should be `github` only). Request body should look like something like this:
```
{
  "clientId": "test",
  "clientSecret": "test"
}
```

After the user post this OAuth app settings create DEX config and rerun DEX with the new config. Navigate the user to the GitHub login flow.

**Comment by sagikazarmark** [comment]
Based on the nature of this *OAuth App* entity, the type should rather be part of the payload, instead of the URL.

**Comment by sagikazarmark** [comment]
Also, every install related API endpoint should be on a separate path, separated from the rest of the code and API.

**Comment by sagikazarmark** [comment]
Closing as we chose a different path for installing Pipeline.
