### ISSUE TITLE
S3 URL for Cloudformation is not accessible. 

### ISSUE THREAD

**Issue by ashishxooa** [banzaicloud/pipeline#2107]
Hey guys, 

The s3 link for cloudformation template to create pipeline on AWS is not accessible 

https://s3-eu-west-1.amazonaws.com/cf-templates-grr4ysncvcdl-eu-west-1/2018079qfE-new.templateejo9oubl16 

Is there an updated link which I can use?

Thanks.

**Comment by stoader** [comment]
Hi @ashishxooa, thanks for reporting this. We need to review our docs and remove obsolete content. 
We reworked how Banzai Cloud Control Plane to make it as simple as possible.
[Here](https://beta.banzaicloud.io/docs/installer/) you can find the details for installing and running a Banzai Cloud Control Plane instance. This will get you a CP instance with a few features preconfigured.

**Comment by ashishxooa** [comment]
@stoader , thanks for the response. I followed the steps to deploy it on my existing k8 cluster. It failed after a point, logs below. 

> Error: rpc error: code = Unknown desc = validation failed: error validating "": error validating data: [ValidationError(StatefulSet.spec): unknown field "strategy" in io.k8s.api.apps.v1.StatefulSetSpec, ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec]
> 
>   on modules/tf-vault/vault.tf line 24, in resource "helm_release" "vault":
>   24: resource "helm_release" "vault" {
> 
> 
> Error: controlplane creation failed: exit status 1
> Usage:
>   banzai controlplane up [flags]
> 
> Aliases:
>   up, c
> 
> Flags:
>   -f, --file string   Input control plane descriptor file (default "values.yaml")
>   -h, --help          help for up
> 
> Global Flags:
>       --color                use colors on non-tty outputs
>       --config string        config file (default is $BANZAICONFIG or $HOME/.banzai/config.yaml)
>       --interactive          ask questions interactively even if stdin or stdout is non-tty
>       --no-color             never display color output
>       --no-interactive       never ask questions interactively
>       --organization int32   organization id
>   -o, --output string        output format (default|yaml|json) (default "default")
>       --verbose              more verbose output
> 
> controlplane creation failed: exit status 1
>  


**Is this something you can help with? I could see some deployments in my helm.** 

> ➜  ~ helm ls --namespace banzaicloud
> NAME       	REVISION	UPDATED                 	STATUS  	CHART                 	APP VERSION	NAMESPACE
> cadence    	1       	Fri Jun 28 16:01:38 2019	DEPLOYED	cadence-0.1.7         	0.5.2      	banzaicloud
> cicd       	1       	Fri Jun 28 16:04:23 2019	DEPLOYED	cicd-2.0.4            	0.8.8      	banzaicloud
> dex        	2       	Fri Jun 28 16:07:58 2019	DEPLOYED	dex-0.0.16            	0.3.4      	banzaicloud
> docs       	1       	Fri Jun 28 16:03:37 2019	DEPLOYED	banzaicloud-docs-0.1.1	1.0        	banzaicloud
> pipeline-ui	1       	Fri Jun 28 16:03:32 2019	DEPLOYED	pipeline-ui-1.1.3     	0.14.0     	banzaicloud
> postgresql 	1       	Fri Jun 28 16:03:45 2019	DEPLOYED	postgresql-4.0.2      	10.7.0     	banzaicloud
> traefik    	1       	Fri Jun 28 15:53:01 2019	DEPLOYED	traefik-1.65.0        	1.7.9      	banzaicloud

**Comment by stoader** [comment]
What Kubernetes version are you running? 

What tiller version is running on your cluster?

**Comment by ashishxooa** [comment]
K8 version is v1.12.8
Tiller version is v2.14.0

**Comment by ashishxooa** [comment]
@stoader I upgraded my k8s cluster to 1.14.1 still the same error.

**Comment by stoader** [comment]
@ashishxooa 

-  download version 0.0.9 from https://github.com/banzaicloud/banzai-cli/releases/tag/0.0.19
- clean up the old installer image: `docker rmi -f banzaicloud/cp-installer:latest`
- re-execute `banzai cp up`

**Comment by ashishxooa** [comment]
@stoader my CLI was already 0.0.19. 

➜  ashish git:(master) ✗ banzai --version
Banzai CLI version 0.0.19 (46ed2a3) built on 2019-06-18T07:59:17Z

**Comment by stoader** [comment]
Did you execute the docker rmi command?

**Comment by ashishxooa** [comment]
Yes, I did that. Cleaned everything and started the process again. 

The up command is still running from 25 minutes and I can see some pods crashing. 
```

➜  k8s-specs git:(master) ✗ kubectl get pods --namespace banzaicloud
NAME                                     READY   STATUS             RESTARTS   AGE
cadence-798446bdbb-4ncb8                 1/1     Running            0          18m
cadence-cassandra-0                      1/1     Running            0          18m
cicd-7b89b68679-2mh4v                    2/2     Running            0          15m
dex-6fc85bdc7d-rj8ww                     1/1     Running            0          14m
docs-banzaicloud-docs-5496f5889f-6tj87   1/1     Running            0          16m
pipeline-6979b56686-xcjhv                0/1     CrashLoopBackOff   7          14m
pipeline-ui-7f9768867c-vw2wt             1/1     Running            0          16m
pipeline-worker-6758c9bf55-24ckg         0/1     CrashLoopBackOff   7          14m
postgresql-postgresql-0                  1/1     Running            0          15m
traefik-c668686d6-4x65t                  1/1     Running            0          20m
vault-0                                  4/4     Running            0          14m
```

Is this normal?

**Comment by stoader** [comment]
can you post logs of the `pipeline-6979b56686-xcjhv` pod?

**Comment by ashishxooa** [comment]
@stoader the process completed now, all the pods are running. The logs indicated a dns issue, maybe route53 took time to update the dns records, I decreased the TTL and update the record again. CP seems to be running right now and I got the UI. 

Thanks! :)
