### ISSUE TITLE
Persist user defined helm repositories 

### ISSUE THREAD

**Issue by sancyx** [banzaicloud/pipeline#2125]
The goal is to able to persist helm repos, so that they are not lost in case of a pod restart plus users of the same organisation can see the same list of repositories.
The solution would be to create a RepositoryStore which will have two implementations: FileRepositoryStore & DBRepositoryStore. Repositories will be stored & fetched from db while repo index file and chart files will still be stored on local filesystem.

**Comment by sagikazarmark** [comment]
Duplicate of #1069 ?
