### ISSUE TITLE
Non deterministic code in the UpdateClusterWorklfow

### ISSUE THREAD

**Issue by mfateev** [banzaicloud/pipeline#2155]
**Describe the bug**
Cadence workflow code must be deterministic to support workflow state recovery through event sourcing. This rules out use of range over map as Go runtime on purpose [randomizes iteration order](https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/).

**Steps to reproduce the issue:**
Execute workflow with [sticky execution off](https://github.com/uber-go/cadence-client/blob/103fa1e95de1a892571ccdef71ebca786e4728cb/internal/worker.go#L170).

**Expected behavior**
The code of all workflows (I've looked at UpdateClusterWorklfow only)  should be rewritten to not use range over map.

**Additional context**
Read [Implementation](https://cadenceworkflow.io/docs/03_goclient/02_create_workflows#implementation) section of the Cadence Go Documentation for more potential determinism gotchas.

**Comment by sagikazarmark** [comment]
Thanks a lot for reporting the issue! We will take a look at it soon!

**Comment by sagikazarmark** [comment]
Done! Thanks for reporting the issue!
