### ISSUE TITLE
AWS: CFM script user data missing variable.

### ISSUE THREAD

**Issue by SherpaPsy** [banzaicloud/pipeline#2180]
Line 462 of the cloud formation script control-plane-cf.template:
           `   cat extra_values.json | jq -r -M --arg jqHelmBanzaiRepositoryURL "${}" '.pipeline.Helm.banzaiRepositoryURL|=$jqHelmBanzaiRepositoryURL' > extra_values.tmp && mv extra_values.tmp extra_values.json`

the value: PIPELINE_HELM_BANZAIREPOSITORYURL is missing - the line should be:

`cat extra_values.json | jq -r -M --arg jqHelmBanzaiRepositoryURL "${PIPELINE_HELM_BANZAIREPOSITORYURL}" '.pipeline.Helm.banzaiRepositoryURL|=$jqHelmBanzaiRepositoryURL' > extra_values.tmp && mv extra_values.tmp `extra_values.json``

**Steps to reproduce the issue:**
Run the cloud formation script and check cloud-init.log

**Expected behavior**
user data script runs without error

**Additional context**
The actual value of the helm repo is also invalid. Will submit another bug for this.

**Comment by stoader** [comment]
@SherpaPsy the `pipeline-cp-launcher` repository is outdated. We should have had archived this repository as we provide a CLI now for deploying Pipeline.

The [0.0.21](https://github.com/banzaicloud/banzai-cli/releases/tag/0.0.21) version supports deploying Pipeline into *existing* K8s cluster. See https://beta.banzaicloud.io/docs/installer/ for deploying Pipeline using the CLI

Note we expect to release by mid-week a new version of the CLI includes additional capabilities such as:
- deploying Pipeline locally into docker
- provisioning infrastructure on AWS for Pipeline deployment

**Comment by sagikazarmark** [comment]
Please use the new installer: https://banzaicloud.com/docs/pipeline/quickstart/
