### ISSUE TITLE
AWS: CFM script has invalid Helm URL for Banzai Cloud repo

### ISSUE THREAD

**Issue by SherpaPsy** [banzaicloud/pipeline#2181]
**Describe the bug**
the default value for this is invalid:
HelmBanzaiRepositoryURL:
    Description: 'The Helm URL to Banzai Cloud stable repository'
    Type: String
    Default: 'http://kubernetes-charts.banzaicloud.com/branch/master'
    ConstraintDescription: Helm repo url

**Steps to reproduce the issue:**
run the cloudformation script and check cloud-init.log to see failure.

**Expected behavior**
user data script completes

**Additional context**
The default URL value: http://kubernetes-charts.banzaicloud.com/branch/master
give this response in browser:
{"error":"not found"}

**Comment by sagikazarmark** [comment]
@SherpaPsy Thanks for reporting this issue.

Actually that URL is redirected to the new repository, so it should work.

Try http://kubernetes-charts.banzaicloud.com/branch/master/index.yaml for instance.

I also checked the code and the example config, and the default value is correct in the code, but not in the example config, so I submitted a PR to fix that.
