### ISSUE TITLE
Do not allow feature actions in case of wrong organization

### ISSUE THREAD

**Issue by colin014** [banzaicloud/pipeline#2195]
**Describe the bug**
I have a GKE cluster with Auto DNS feature. I want to list the feature details (`/pipeline/api/v1/orgs/2/clusters/{clusterID}/features/dns`) i got the right response. After i change the organization (from `colin014`(2) to `banzaicloud`(10)) i still got the right response but the cluser isn't belong to `banzaicloud` organization.

I can do any action (like active & deactivate) on features of cluster

**Expected behavior**
Do not allow any action with feature on clusters which not belongs to the organization. Check the organization with the organization of the cluster.

**Comment by sagikazarmark** [comment]
IMHO this should be generalized to every cluster action. 

If Cluster 123 is in org 1 then `/orgs/2/clusters/123` is not valid.
