### ISSUE TITLE
offer installing vault-secrets-webhook as a feature

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/pipeline#2206]
**Is your feature request related to a problem? Please describe.**
We would like to offer to install the vault-secrets-webhooks chart as the cluster creation flow.

**Describe the solution you'd like to see**
Offer it as a configurable feature.

**Describe alternatives you've considered**
N/A

**Additional context**
We would like to make installing this webhook easier on the cluster that has been provisioned by Pipeline.

**Comment by sagikazarmark** [comment]
Implemented as Bank-Vaults integrated service.
