### ISSUE TITLE
EKS: Implement 'waitForASGToBeFulfilled' as cadence activity

### ISSUE THREAD

**Issue by stoader** [banzaicloud/pipeline#2504]
The creation of EKS node pools includes a step which waits for the underlying ASG to be fulfilled (actual VM instance count = desired VM instance count).

This step should be split out into a separate cadence activity that sends heartbeats as long as it's still waiting for the ASG to be fulfilled.

**Comment by siliconbrain** [comment]
Wouldn't it be better to send a signal when the ASG has the required number of VMs?
