### ISSUE TITLE
404 after deployment of piplineCI

### ISSUE THREAD

**Issue by bobbych** [banzaicloud/pipeline#256]
Hi All,

I am trying to install pipeline api server on aws, from instructions [here](https://github.com/banzaicloud/pipeline/blob/master/docs/pipeline-howto.md). But i am trying to access pipeline manager of api i am getting `404`. 
```
curl http://x.x.x.x/pipeline/api/v1
404 page not found
```
when i try it in browser its redirects to `{public ip}\authorize` and return `404` as well. I can see app registered in my Github

Any Help is appreciated!
Thanks!
Bobby
![banzai_git](https://user-images.githubusercontent.com/5950589/37235034-4de2fddc-23b0-11e8-9e9e-ee742d61b8a0.jpg)

BTW  `prometheus` and `grafana` seems to work

**Comment by bonifaido** [comment]
Hi @bobbych,

First of all, thank you for trying out the Pipeline!

http://x.x.x.x/pipeline/api/v1 is just a subpath in our API and currently doesn't return anything (however I have just created an issue to return our API map at this endpoint as just like Kubernetes does, see https://github.com/banzaicloud/pipeline/issues/257).

You can find the possible valid path postfixes currently here (our Swagger documentation is in the making): https://github.com/banzaicloud/pipeline/blob/master/main.go#L107

So for example to list your clusters you have to call: `http://x.x.x.x/pipeline/api/v1/clusters`
To get and API token you have to call: `http://x.x.x.x/pipeline/api/v1/token`

I hope this helps.

**Comment by bonifaido** [comment]
I forgot to mention that on Wednesday we will have a new release where we will have OAuth enabled for the whole Pipeline API and things will be probably more straightforward. ;-)

**Comment by bobbych** [comment]
@bonifaido thanks for the tip, got a little further with this, i was able to deploy to aws using cloud formation (using "latest" tag) and pass the auth part . I started using postman examples using Bear token shown in UI,  made request to

```
http://x.x.x.x/api/v1/clusters
Response 200

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="version" content="0.8.2">
        <script>
	window.DRONE_USER = {"id":1,"login":"xxxx","email":"","avatar_url":"https://avatars3.githubusercontent.com/u/xxxxxxx?v=4","active":true,"synced":1521058449};
	window.DRONE_SYNC =  false ;
</script>
        <script>
	window.DRONE_CSRF = " <token is printed here> "
</script>
        <link rel="shortcut icon" href="/favicon.png">
    </head>
    <body>
        <script type="text/javascript" src="/static/vendor.083efb00670e0f927f32.js"></script>
        <script type="text/javascript" src="/static/bundle.d1a94d49a07c34299724.js"></script>
    </body>
</html>

```

and also tried making requested using `pipeline` endpoint, i am getting

```
http://x.x.x.x/pipeline/api/v1/clusters
{
    "code": 401,
    "message": "Invalid token",
    "error": "Error making API request.\n\nURL: GET http://dapper-tortoise-vault:8200/v1/secret/accesstokens\nCode: 403. Errors:\n\n* permission denied"
}
```

**Comment by bobbych** [comment]
@bonifaido thanks for your response. I was able to get it to go past auth and have ui working, btw i deployed to aws using cloud formation template (`latest` tag. Tag `0.3.0` as documented on `pipeline-cp-launcher` does not exist yet). When i tried to use postman examples to create clusters, with Bearer token displayed on UI

```
POST http://x.x.x.x/api/v1/clusters

body: {
  "name":"awscluster-bobby-1",
    "location": "eu-west-1",
    "cloud": "amazon",
    "nodeInstanceType": "m4.xlarge",
    "properties": {
        "amazon": {
            "node": {
                "spotPrice": "0.2",
                "minCount": 1,
                "maxCount": 2,
                "image": "ami-06d1667f"
            },
            "master": {
                "instanceType": "m4.xlarge",
                "image": "ami-06d1667f"
            }
        }
    }
}

Response: 

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
            <meta name="version" content="0.8.2">
                <script>
	window.DRONE_USER = {"id":1,"login":"xxxxx","email":"","avatar_url":"https://avatars3.githubusercontent.com/u/xxxxxx?v=4","active":true,"synced":1521058449};
	window.DRONE_SYNC =  false ;
</script>
                <script>
	window.DRONE_CSRF = "<token printed here>"
</script>
                <link rel="shortcut icon" href="/favicon.png">
                </head>
                <body>
                    <script type="text/javascript" src="/static/vendor.083efb00670e0f927f32.js"></script>
                    <script type="text/javascript" src="/static/bundle.d1a94d49a07c34299724.js"></script>
                </body>
            </html>
```

Also tried with `pipeline` endpoint
```
POST http://x.x.x.x/pipeline/api/v1/clusters

body: {
  "name":"awscluster-bobby-1,
    "location": "eu-west-1",
    "cloud": "amazon",
    "nodeInstanceType": "m4.xlarge",
    "properties": {
        "amazon": {
            "node": {
                "spotPrice": "0.2",
                "minCount": 1,
                "maxCount": 2,
                "image": "ami-06d1667f"
            },
            "master": {
                "instanceType": "m4.xlarge",
                "image": "ami-06d1667f"
            }
        }
    }
}

Response: 

{
    "code": 401,
    "message": "Invalid token",
    "error": "Error making API request.\n\nURL: GET http://dapper-tortoise-vault:8200/v1/secret/accesstokens\nCode: 403. Errors:\n\n* permission denied"
}
```

**Comment by bonifaido** [comment]
@bobbych we are in the middle of the release and because of this the documentation is a bit out of sync with the exact git tags. Could you please try the `master` branch from https://github.com/banzaicloud/pipeline-cp-launcher to start a cluster? I just tried now with the latest master and I successfully managed to call the API `http://34.xxx.xxx.xx/pipeline/api/v1/clusters`

**Comment by stoader** [comment]
@bobbych sorry for the inconvenience. The postman collection referred in the README wasn't refreshed thus was pointing to an outdated one.

Can you try the updated postman collection from https://github.com/banzaicloud/pipeline#create-and-scale-your-cluster ?

Also you'll need to pass an `bearer` access token to the REST API call which you can obtain from https://github.com/banzaicloud/pipeline/blob/master/docs/github-app.md#acquiring-the-access-token

**Comment by bonifaido** [comment]
Hi @bobbych !
I'm happy to inform you that our 0.3.0 release just went out yesterday, so could you please try out with that new version?

**Comment by bobbych** [comment]
@bonifaido seems to work now, thank you!
