### ISSUE TITLE
Adding existing repository to CICD fails

### ISSUE THREAD

**Issue by stoader** [banzaicloud/pipeline#2564]
**Describe the bug**
Unable to add an existing repository to CICD as it fails with "Something went wrong error message"

**Steps to reproduce the issue:**
Launch any Spotguide than delete it. Navigate to the CICD page on the UI, click a repository and select the repository that was previously created by the Spotguide.

**Expected behavior**
Being able to add existing repository to CICD, also in case of error to see the root cause that helps diagnosis instead of generic "Something went wrong" message.

**Screenshots**
<img width="710" alt="image" src="https://user-images.githubusercontent.com/6655123/69870191-5ef65480-12af-11ea-84b9-07d8cf224ee7.png">

**Additional context**
Apparently the API call used behind the scenes ```POST https://<pipeline-url>/api/repos/<org-name>/<repo-name>``` fails with error code 400 ```{"error ":"invalid JSON in body"}```

**Comment by bonifaido** [comment]
Just checked this, the URL wrong here, the UI should call `POST https://<pipeline-url>/build/api/repos/<org-name>/<repo-name>` so the `build/` path segment is missing here.

**Comment by bonifaido** [comment]
Was fixed in the UI repository.
