### ISSUE TITLE
Expiration integrated service

### ISSUE THREAD

**Issue by siliconbrain** [banzaicloud/pipeline#2577]
The service's main objective is to reduce cluster-related cost by discarding expensive resources automatically at a preset time.
The service does not work with imported clusters where Pipeline has no control over high-cost infrastructure resources.
Notifications should be sent about failed expiration jobs (and maybe even successful ones).

Inputs:
- time of expiration (point in time, absolute, UTC?)

Outputs:
*none*

UI notes:
- allow for time of expiration to be specified as time delta (e.g. *in 2 hours*) starting from activation
  - this is for UX only, API expects absolute time
- show warning if time delta is small (e.g. <30min) and cluster is in `CREATING` state
- as output, show countdown based on expiration time

Implementation notes:
- resource disposal should be handled by the cluster-specific delete flow
- expiration jobs should be cancelled by service deactivation with best-effort
  - might apply to service update too
- expiration jobs must survive control plane reboots (i.e. state loss) conservatively (use *at-least-once* policy with idempotent delete)
- expiration job runs independent of cluster state (i.e. even if cluster status is `ERROR`)
  - how about `DELETING`? shouldn't matter with idempotent delete, but should wait for success.

Out of Scope:
- fix cluster deletion flows (see https://github.com/banzaicloud/pipeline/issues/2576)
- implementing a full-fledged notification framework -> v1.5

**Comment by siliconbrain** [comment]
We won't handle changes to timezones that occur after service activation. (At least not in v1.) This would incur a maintenance cost, as such changes are hard to detect automatically.

**Comment by sagikazarmark** [comment]
Done
