### ISSUE TITLE
Make SSH key generation in EKS configurable

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pipeline#2678]
**Is your feature request related to a problem? Please describe.**
Customers might not want us to create SSH keys for their EKS clusters.

**Describe the solution you'd like to see**
Make SSH key creation configurable.

**Comment by orymate** [comment]
Is this about a pipeline config value, a cluster creation request parameter, or both?

**Comment by sagikazarmark** [comment]
Pipeline config
