### ISSUE TITLE
Deleting clusters on Amazon fails

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pipeline#2683]
**Describe the bug**
Force deleting resources for the first time fails on Amazon.

In case of EKS IAM user is not deleted.

In case of PKE Master pool and VPC stays there.

**Steps to reproduce the issue:**
1. Create new PKE/EKS cluster
2. Install backyards on it
3. Install demo application
4. Force delete the cluster

**Expected behavior**
All cluster resources should be deleted

**Additional context**
You can check the resources on AWS Console, under Cloudformation.

Chances are ELB deletion fails, causing the force delete to fail.

**Comment by lpuskas** [comment]
could reproduce it:
- master  and vpc cloudformation templates not deleted, while the cluster (forcibly) deleted from pipeline.
Investigating it further

**Comment by lpuskas** [comment]
found the issue - workflow activities time out before operations in cloud are finished, thus resource deletions after such an event are skipped.

Fix is underway.
