### ISSUE TITLE
hpa-operator causes operator-sdk based operators to fail

### ISSUE THREAD

**Issue by khernyo** [banzaicloud/pipeline#2748]
**Describe the bug**
Operators built using operator-framework/operator-sdk from helm charts don't work on pipeline created k8s clusters.

**Steps to reproduce the issue:**

1. create a k8s cluster using pipeline (any of EKS 1.14, PKE 1.15 or PKE 1.17, possibly others)
1. install sample helm based memcached-operator by following the instructions at https://github.com/operator-framework/operator-sdk-samples/tree/master/helm/memcached-operator
1. observe that no memcached pods are created

Note: the go based memcached-operator is not affected.

**Expected behavior**
memcached-operator creates three memcached pods

**Additional context**
pipeline 0.39.0-dev.6 (61a9abf62)

Error log from memcached-operator:
```
{
  "level": "error",
  "ts": 1582549445.626265,
  "logger": "controller-runtime.controller",
  "msg": "Reconciler error",
  "controller": "memcached-controller",
  "request": "helm-memcached/example-memcached",
  "error": "failed to install release: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: Got empty response for: custom.metrics.k8s.io/v1beta1",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"
}
```

Deleting the hpa-operator (`helm delete --purge hpa-operator`) solves the issue.

Possibly related: https://github.com/banzaicloud/hpa-operator/issues/17
Note: the linked [PR](https://github.com/kubernetes/kubernetes/pull/71190) to fix the bug was not merged.

**Comment by sancyx** [comment]
This issue https://github.com/helm/helm/issues/6361 has been workarounded in Helm 3 https://github.com/helm/helm/pull/6908/files, however is yet available in version 2.

**Comment by sancyx** [comment]
related to https://github.com/banzaicloud/pipeline/issues/2806

**Comment by sagikazarmark** [comment]
We are on Helm 3, it should resolve the issue.
