### ISSUE TITLE
Helm deployments fail in case there are api extension returning with empty versions

### ISSUE THREAD

**Issue by sancyx** [banzaicloud/pipeline#2806]
**Describe the bug**
There's a bug currently in k8s client lib, which treats as an error if an API extension endpoint returns an empty list. In case of metrics API extensions (metrics.k8s.io, custom.metrics.k8s.io, external.metrics.k8s.io) an empty list is returned until there are metrics to expose. Once you install a metrics API extension on cluster and while there are no gathered metrics all Helm deployments will fail.
There's a workaround in Helm v3 https://github.com/helm/helm/pull/6908/files, not yet ported to Helm 2.15/2.16. 
This https://github.com/banzaicloud/pipeline/pull/2788 may improve the situation, but probably doesn't resolves entirely.

**Steps to reproduce the issue:**
Create cluster.

**Expected behavior**
Should not fail.

**Comment by sagikazarmark** [comment]
We are on Helm 3, it should resolve the issue.
