### ISSUE TITLE
Local quickstart setting kind to 127.0.0.1

### ISSUE THREAD

**Issue by Opswatch** [banzaicloud/pipeline#2846]
**Describe the bug**
Trying to follow the https://banzaicloud.com/docs/pipeline/quickstart/install-pipeline/local/ instructions.

According to this note "If your machine (especially the TCP 443 port) is accessible from the Internet, you can set the external IP address or FQDN as the external hostname of your installation, and run banzai pipeline up again."

When trying to set a FQDN it keeps binding it to 127.0.0.1 not allowing routing from a remote machine.

When trying to use a static ip I get the following error: 

Error: rpc error: code = Unknown desc = timed out waiting for the condition

  on modules/tf-pipeline/pipeline.tf line 46, in resource "helm_release" "pipeline":
  46: resource "helm_release" "pipeline" {

**Steps to reproduce the issue:**
Setup a ubuntu 18.04 vm assign it a static ip with a FQDN in the hosts file, follow the quickstart instructions to setup a local environment using kind.

**Expected behavior**
Expect the setup to use either the static ip or the FQDN instead of binding to 127.0.0.1

**Additional context**
Ubuntu 18.04 with docker 18.09.9

**Comment by orymate** [comment]
Thanks for reporting the issue. We have released a new Banzai CLI version which contains a fix that allows setting the kind bind address.

The quickstart guide will be updated with the following text:
> If your machine (especially the TCP 443 port) is accessible from the Internet, you can set the external IP address or FQDN as the [external hostname] (../../../configuration/domain-name/) of your installation and `providerConfig.listenAddress` to `0.0.0.0` in the values file. Note that if you have already deployed Pipeline, you have to re-create the kind cluster to take this change effect by running `banzai pipeline down`, and running `banzai pipeline up` again.
