### ISSUE TITLE
Add us-gov region functionality to Banzai UI

### ISSUE THREAD

**Issue by mward29** [banzaicloud/pipeline#3008]
**Is your feature request related to a problem? Please describe.**
Unable to create or modify clusters built in us-gov regions from the Banzai UI.

**Describe the solution you'd like to see**
Would like to be able to build and modify clusters located in us-gov as is possible in other AWS regions.

**Describe alternatives you've considered**
The current alternative is to do this via command line.

**Additional context**
<img width="1693" alt="Screen Shot 2020-07-10 at 11 04 39 AM" src="https://user-images.githubusercontent.com/1389176/87174900-7c57bc00-c29d-11ea-96d2-ff25a35507e0.png">

**Comment by sagikazarmark** [comment]
Thanks for reporting this issue. We will look into it.

**Comment by sagikazarmark** [comment]
This was actually an issue in cloudinfo which has been resolved by configuring it to use gov-cloud.
