### ISSUE TITLE
Failed node pool creates leave behind non-deleteable resources

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pipeline#3031]
**Describe the bug**
When a node pool create fails, the cloudformation stack stucks in an error state and it cannot be deleted with node pool delete. As a result, the same node pool name cannot be reused.

**Steps to reproduce the issue:**
1. Create a new node pool with an AMI from a different region
1. Let it fail.
1. Try to delete the node pool

**Expected behavior**
Deleting a failed node pool should succeed.

**Additional context**
We have no information about how deleting a failed node pool fails.

In the future, we should probably clean up the failed resources. We should decide whether we wait until the process log becomes GA or go ahead and implement the clean up logic. The important thing is to get the error.

**Comment by pregnor** [comment]
There are 3 different sub-issues connected to this problem:
1. The `Create-/DeleteNodePool` operations don't propagate their errors up to the cluster status level - this is an oversight in the error handling logic.
2. The failed `CreateNodePool` operation fails fast and loud at a point before the node pool would be registered in the Pipeline's domain. Also the failed creation does no cleanup afterwards. 
3. The `DeleteNodePool` operation on such a failed-to-create node pool is never executed, a `204 No Content` response is returned, because the `DeleteNodePool` operation finds no corresponding node pools to delete in the Pipeline's domain and assumes the node pool was deleted beforehand successfully and thus returns a success indicator without actually doing anything.

**Comment by pregnor** [comment]
Example creation error: (reproducible with an out-of-region AMI ID)
```
client error: waiting for CF stack create operation to complete failed: stack pipeline-eks-nodepool-pregnor-local-200728-pipeline-3031-2-node-pool-10
pipeline-eks-nodepool-pregnor-local-200728-pipeline-3031-2-node-pool-10 CREATE_FAILED The following resource(s) failed to create: [NodeGroup]. 
NodeGroup CREATE_FAILED You must use a valid fully-formed launch template. The image id '[ami-064fd810d76e41b31]' does not exist (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: fa5ee299-af41-4edd-ad35-fddab97c7f6a)
```

Example create retry error: (reproducible with a valid node pool request using the node pool name of a failed-to-create node pool)
```
could not create 'pipeline-eks-nodepool-pregnor-local-200728-pipeline-3031-2-node-pool-10' CF stack: TokenAlreadyExistsException: The client request token d9e96024-65c7-4c5d-b135-4e3e3c684825-eks-create-asg has already been used for this stack. Retry the request with a different client request token
        status code: 400, request id: 61f4db33-c1c1-41b2-a537-579dfbcdd969
```

**Comment by pregnor** [comment]
Solution proposal:
1. The error propagation logic needs to be fixed.
Note: this should also be incorporated into other similar operations where the cluster status error is set similarly.

2. & 3. 
    a, either the creation operation has to be made atomic and thus it has to clean up after itself, 
        - This is also easier if b, is implemented on a lower level - e.g. the operation steps have their inverse operation step defined including failed state handling. 🙂 
        - Every step of the operation has to handle an error by undoing the previously executed operation steps - at least for steps mutating any resources persisting throughout the parent cluster's lifecycle and beyond.

    b, the creation&deletion operation pair has to be made the exact inverse of each other so a (creation + deletion) operation chain is an idempotent operation on the cluster level - for all cases including intermediate failures.
        - The deletion should rely on information available from creation start to determine whether any resource deletion is required which can be achieved with an earlier Pipeline domain registration step or it should try deleting resources regardless of their local domain status and should check their existence in other domains or alternatively allow deletion failures due to the underlying resources actually not existing.

4. The node pool creation should use a client request token which is unique to the operation such as the operation ID.
Note: this should also be incorporated into other similar operations where a client request token is used.
Also the solution for 2.&3. should resolve the second half of this issue.

**Comment by pregnor** [comment]
We discussed this and came to the conclusion that short-term-wise we want to record the failed-to-create node pools as well internally and do the deletion based on that with skip-if-not-exist approach to all node pool resources during deletion of such a failed-to-create node pool.
