### ISSUE TITLE
Add envelope encryption support to EKS

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pipeline#3088]
**Is your feature request related to a problem? Please describe.**
As a user concerned about security, I want etcd to be encrypted.

**Describe the solution you'd like to see**
On EKS, envelope encryption provides that feature, but it can only be enabled/disabled when the cluster is launched.

Make this feature available when launching an EKS cluster.

**Describe alternatives you've considered**
In case of managed distributions, there aren't really any alternatives.

**Additional context**
https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-eks-adds-envelope-encryption-for-secrets-with-aws-kms/

**Comment by pregnor** [comment]
More info:
On EKS envelope encryption: https://aws.amazon.com/blogs/containers/using-eks-encryption-provider-support-for-defense-in-depth/
On creating customer master keys: https://docs.aws.amazon.com/kms/latest/developerguide/create-keys.html

**Comment by pregnor** [comment]
Based on the sources 6 and 7, the API cluster creation request should contain an encryption configuration object similar to the following one:
```json
{
    "encryptionConfig": [ 
        { 
            "provider": { 
                "keyArn": "arn:aws:kms:<REGION>:000000000000:key/00000000-0000-0000-0000-000000000000"
            },
            "resources": [ 
                "secrets"
            ]
        }
    ]
}
```

Notes:
- The keyArn field may contain the CMK key ARN or an alias to it.
- The resources field defines which resources should be encrypted using the configuration, currently only the `secrets` value is supported.

**Comment by pregnor** [comment]
The `aws-sdk-go` package only supports the encryption config cluster creation input parameter from [v1.29.18](https://github.com/aws/aws-sdk-go/pull/3187) which means we have to update our dependency from the current v1.28.2 version.

**Comment by pregnor** [comment]
The CMK key ARN/alias needs to be propagated from the Pipeline API's cluster create request to [here](https://github.com/banzaicloud/pipeline/blob/master/internal/cluster/distribution/eks/eksprovider/workflow/create_eks_control_plane_activity.go#L157) once we updated the `aws-sdk-go` dependency.
