### ISSUE TITLE
EKS cluster version upgrade

### ISSUE THREAD

**Issue by balazsbc** [banzaicloud/pipeline#3094]
For supporting cluster version upgrades we start with EKS.

Pipeline currently supports Kubernetes versions on EKS from 1.14 to 1.17

According to the [official EKS guide](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html) the following steps are needed for upgrading the Kubernetes master node:

1. Update the cluster `version` with the [update API call](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#EKS.UpdateClusterVersion)
2. Wait of the update to be finished with [describe API call](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#EKS.DescribeUpdate)
3. Save the new version information to the DB.
**This is where the open-source version ends.**
4. Update image in the `kube-proxy` DaemonSet on the cluster according to the `version`:
    ```bash
    kubectl set image daemonset.apps/kube-proxy \
        -n kube-system \
        kube-proxy=602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.17.7
    ```
5. Patch the AWS VPC CNI image version in the `aws-node` DaemonSet, according to the above-linked docs if it is earlier than `1.6.3`:
    ```bash
    kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
    ```

**NOTE:** GPU nodes must update the NVIDIA device plugin DaemonSet, but that is not in-scope for this task.

Implementation details:
- Implement this in an `eks-update-cluster` workflow - specifically for each provider behind the same API call.
- We can reuse the already existing Pipeline API [endpoint](https://github.com/banzaicloud/pipeline/blob/master/apis/pipeline/pipeline.yaml#L176) as a frontend for this when the future `version` attribute changes we start the upgrade.

**Comment by bonifaido** [comment]
Open-source version done, enterprise version tracked in that repository.
