### ISSUE TITLE
chore(term): consolidate EBS volume size measurement units to GiB

### ISSUE THREAD

**Issue by pregnor** [banzaicloud/pipeline#3162]
**Is your feature request related to a problem? Please describe.**

GB unit is used throughout the code base for description, while the [AWS EC2 instance EBS VolumeSize definition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-template.html) states the unit is GiB instead.

**Describe the solution you'd like to see**

Replace the GB references with GiB.
Note: the values are transferred transparently through integer holders so this does not have an impact on code execution, it is merely for clarifying the documentation of the corresponding variables and meeting the end user expectations and relations between the value put in and the resulting volume size.

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by akijakya** [comment]
This issue got resolved in PR #3593
