### ISSUE TITLE
Handle pke bootstrap errors in cluster creation

### ISSUE THREAD

**Issue by orymate** [banzaicloud/pipeline#3176]
If the PKE bootstrap ends with error (as per the exit code sent to the new api endpoint from #3174), terminate the cluster creation and set ERROR state (all cloud providers).

May use the same signal that's sent when the first master calls back to /ready with the config.

**Comment by sagikazarmark** [comment]
> May use the same signal that's sent when the first master calls back to /ready with the config.

What does that mean? You don't need to use the same signal, you can have a separate signal or just send a cancellation request to the workflow. But that's an implementation detail.
