### ISSUE TITLE
docker-compose up says access denied

### ISSUE THREAD

**Issue by sodre90** [banzaicloud/pipeline#45]
When I try to start banzai pipeline with "docker-compose up", I get the following error message:
ERROR: pull access denied for banzaiclouds/pipeline-prod, repository does not exist or may require 'docker login'

maybe the docker-image is private

**Comment by matyix** [comment]
Koszi @sodre90  - thanks for reporting.

There is a bug in docker-compose trying to re-authenticate if the image was not built by Docker Hub (through automated build) or you are not part of the org.

```
compose.service.pull: Pulling app (banzaiclouds/pipeline-prod:72)...
compose.cli.verbose_proxy.proxy_callable: docker pull <- (u'banzaiclouds/pipeline-prod', tag=u'72', stream=True)
docker.auth.get_config_header: Looking for auth config
docker.auth.get_config_header: No auth config in memory - loading from filesystem
docker.auth.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.auth.find_config_file: No config file found
docker.auth.resolve_authconfig: Looking for auth entry for 'docker.io'
docker.auth.resolve_authconfig: No entry found
docker.auth.get_config_header: No auth config found
ERROR: compose.cli.errors.log_api_error: pull access denied for banzaiclouds/pipeline-prod, repository does not exist or may require 'docker login'
``` 
Currently our images are built by CircleCI and pushed to Docker Hub, however they are all public (see normal `docker pull`). Still thinking on a solution to fix this and will get back to you.
