### ISSUE TITLE
Spotguide descriptor

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/pipeline#480]

**Comment by stoader** [comment]
This is an example for spot guide descriptor. This may change over time as support for new spot guides being added:

`resources:
  - vcpu: 32
    memory: 32G
    filter:
      - gpu
      - ena
      - boostable
      - high-iops
     # Percentage of on demand VMs across the entire cluster
     on_demand_percentage: 50%
     # Whether VMs should be the same size or not
     same_size: true

options:
  - name: spark-rss
    type: boolean
    info: "Spark Resource Staging Server"
    default: true
    key: historyServer.enabled

  - name: spark-hs
    type: boolean
    info: "Spark History Server"
    default: true
    key: shuffle-hs.enabled

  - name: spark-shuffle
    type: boolean
    info: "Spark External Shuffle Service"
    default: true
    key: spark-shuffle.enabled
    readonly: false

  - name: monitor
    type: boolean
    info: "Prometheus Monitoring"
    default: true
    key: pipeline-cluster-monitor.enabled

  - name: logging
    type: boolean
    info: "Fluentd Monitoring"
    default: true
    key: pipeline-cluster-log.enabled

depends:
  - monitor:
      type: crd
      values: 
          - prometheuses.monitoring.coreos.com
          - servicemonitors.monitoring.coreos.com
          - alertmanagers.monitoring.coreos.com
      namespace: monitoring
      charts:
        - name: pipeline-cluster-monitor
          repository: alias:banzaicloud-stable
          version: 0.0.1
  - logging: 
      type: chart
      namespace: default
      charts:
        - name: pipeline-cluster-log
          repository: alias:banzaicloud-stable
          version: 0.0.1`

**Comment by tarokkk** [comment]
Obsolete since Spotguide rethinking
