### ISSUE TITLE
Handle in-progress ClusterCreation

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/pipeline#498]
When a cluster creation is in Progress with name `cluster1` and another cluster creation request arrives with the same name `cluster1` the second request shouldn't fail but return `HTTP 20x` marking that the creation is in-progress. This change should be made in correlation with https://github.com/banzaicloud/drone-plugin-pipeline-client

**Comment by sagikazarmark** [comment]
Sounds like 201 would be a perfect candidate. I would also handle the case when the cluster is being deleted when a creation request is sent: that should probably be 409 (Conflict)
