### ISSUE TITLE
Return specific errors from `secretStore` methods

### ISSUE THREAD

**Issue by stoader** [banzaicloud/pipeline#505]
Instead of returning generic errors from the methods of `secretStore` return specific errors, this will enable callers to be able to handle differently the various types of errors that may occur with secrets.

Currently the caller has to check the message of the error message to differentiate the errors which is an error prone solution.

**Comment by sagikazarmark** [comment]
The secret store already returns ErrSecretNotFound, I'm not aware of any other usecases where this might count.
