### ISSUE TITLE
Can not install a specific secret to cluster

### ISSUE THREAD

**Issue by stoader** [banzaicloud/pipeline#617]
**Is your feature request related to a problem? Please describe.**
The `InstallSecrets` method takes `ListSecretsQuery` as parameter to filter the secrets to be installed into a cluster. This doesn't allow for installing a specific secret only.

**Describe the solution you'd like to see**
We should be able to install one specific secret using `InstallSecrets`

**Comment by bonifaido** [comment]
Fixed already, query by tag, or with specific name is already supported.
