### ISSUE TITLE
Authenticate Kubernetes Dashboard explicitly through proxy

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/pipeline#731]
Currently, the login popup will challenge the user when accessing the Kubernetes Dashboard and will ask an authentication mechanism. This can be skipped right now and will authenticate with the ServiceAccount of the Kubernetes Dashboard pod. See: https://github.com/kubernetes/dashboard/wiki/Access-control for more details.

**Comment by sagikazarmark** [comment]
We don't install the dashboard anymore.
