### ISSUE TITLE
Dynamically manage Storage Classes with PVC Operator 

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/pipeline#902]
Support for multiple storage class usage. 

Different applications require different storage solutions. Many cloud providers add a default storage class which will be used when the storage class name is not specified. With the [Banzai Cloud PVC operator](https://github.com/banzaicloud/pvc-operator) we can allow using more application-aware storage solutions - the PVC operator can create storage classes.

Useful for #899

**Comment by sagikazarmark** [comment]
PVC operator is not installed anymore
