### ISSUE TITLE
Update EKS to use lates CloudFormation template

### ISSUE THREAD

**Issue by stoader** [banzaicloud/pipeline#992]
Update EKS to use latest CloudFormation templates and AMIs: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html#vpc-create

While updating the latest CloudFormation templates we need to preserve our customisations in the CF templates:
* support for spot instances: https://github.com/banzaicloud/pipeline/blob/master/templates/eks/amazon-eks-nodepool-cf.yaml#L255
https://github.com/banzaicloud/pipeline/blob/master/templates/eks/amazon-eks-nodepool-cf.yaml#L265-L266
https://github.com/banzaicloud/pipeline/blob/master/templates/eks/amazon-eks-nodepool-cf.yaml#L355
* node labelling /w nodepool name: https://github.com/banzaicloud/pipeline/blob/master/templates/eks/amazon-eks-nodepool-cf.yaml#L382
* ssh to nodes: https://github.com/banzaicloud/pipeline/blob/master/templates/eks/amazon-eks-nodepool-cf.yaml#L316

**Comment by sancyx** [comment]
https://github.com/banzaicloud/pipeline/commit/c4b9a92f3625ce61bfccc47a6dfb8a0d020d83e5
